### PR TITLE
Unit 2 proposal updates

### PR DESCRIPTION
**Pull request by PierreCounathe**
- Update link to FrozenLake environment documentation (from link to gymlibrary.dev that leads to the screenshot below to link to gymnasium.farama.org)
- Add a missing parameter in a function's docstring
- Change action-value description to match previous wording and to be more precise
- Small details (missing space, useless comma, wording)

Multiple commits so you can cherry pick changes.

## Screenshot for bullet point 1
Screenshot 2023-08-27 at 11 14 38 PM

### CODE REVIEW

**Comment by PierreCounathe** [comment]
Hey @simoninithomas, there is another small change I want to make, related to the agent position calculation in the notebook and the `hands-on.mdx`. ([Issue described here](https://github.com/Farama-Foundation/Gymnasium/issues/692))

I did not solve it before because the issue comes from Farama, so I wanted their confirmation first. They merged my [PR](https://github.com/Farama-Foundation/Gymnasium/pull/695#event-10209145046) solving this issue. Do you want me to add the changes on this PR or in a separate one for better visibility as you already put this one in the next monthly update?

**Comment by simoninithomas** [comment]
If possible a separate one please. Thanks for you help🤗

**Comment by PierreCounathe** [comment]
Cool, just opened [another one](https://github.com/huggingface/deep-rl-class/pull/395) @simoninithomas.

**Comment by simoninithomas** [comment]
Hey there 👋 thanks again I'm going the update today so I merge it. I'm just testing first that everything is working 🤗

**Pull request merged**
