### PR TITLE
Create glossary.mdx

### PR DESCRIPTION
**Pull request by ramon-rd**
Init the glossary for unit 2 and added the strategies to find the optimal policy and the value-based methods studied in the unit.

### CODE REVIEW

**Comment by simoninithomas** [comment]
Hey there 👋 , nice work 🤗. I think there's other terms that you and classmates can add to the glossary: Q-Learning, Q-Function, Epsilon greedy / Greedy strategy, Monte Carlo, TD.

**Comment by ramon-rd** [comment]
Sure! I will add some of them during the rest of the week.

**Comment by osanseviero** [comment]
Related to: #128

**Comment by osanseviero** [comment]
@simoninithomas should we merge this as discussed and then let people add new PRs? That way we have the content up for people in unit 2 and we develop this iteratively :)

**Comment by osanseviero** [comment]
FYI #128 has a couple of ideas we could add here

**Pull request merged**
