### PR TITLE
Super tiny fix format

### PR DESCRIPTION
**Pull request by fzyzcjy**
Hi thanks for the course! It seems that here a newline is missing.

image

### CODE REVIEW

**Comment by simoninithomas** [comment]
Hey, thanks for pointing this out 🤗 I'm checking the preview and merge it

**Comment by simoninithomas** [comment]
It seems the problem is not solved yet. https://moon-ci-docs.huggingface.co/learn/deep-rl-course/pr_420/en/unit4/policy-gradient

**Comment by fzyzcjy** [comment]
Totally agree the dots are not there, but at least one thing for one line ;)

Btw, it seems that all latex and words do not have a space in between.

image

**Comment by simoninithomas** [comment]
Yeah that's weird 🤔 . I'm adding this PR for the next update.

**Pull request merged**
