### PR TITLE
Fixed typeset in (optional) policy gradient theorem

### PR DESCRIPTION
**Pull request by vicha-w**
Hi,

I am currently following HuggingFace's Deep RL course. The course is great so far, but I can't help but notice an error in the math typeset in optional chapter about the policy gradient theorem. I have fixed that in this pull request.

However, I believe we can have better typeset on the tutorial just like in calculus textbook, but I need to understand the typeset system you are using in the tutorials to work further, especially how does it show mathematical equations. I have an extensive experience in typesetting with LaTeX, so I think I can help if the syntax closely resembles that language.

Please let me know if you would like me to help with the typeset. I would _love_ to see a nice, textbook-like typeset in this optional chapter.

Thanks!
Vichayanun

### CODE REVIEW

**Comment by simoninithomas** [comment]
Hey there

Our latex is like this \\( YOUR LATEX HERE //)


But your change lead to a problem, you removed the content in "we can rewrite as"

Screenshot 2024-05-02 at 08 59 08

**Comment by simoninithomas** [comment]
I run a build PR so that you can see what it looks like (it will take 5min to build)

**Comment by vicha-w** [comment]
Hi Thomas,

I have checked the latest build, and I do not see the problem with my change, so let me explain what I fixed in this PR.

Here is the text in the current build, live on HuggingFace.

ภาพถ่ายหน้าจอ 2567-05-02 เวลา 14 43 56

As you can see, there is excess text after "Thus we can rewrite the sum as" which I have highlighted in the red box and should be moved to the previous line. Here is the fixed version on CI:

ภาพถ่ายหน้าจอ 2567-05-02 เวลา 14 46 04

Please let me know if that does not actually work in this case.

Thanks!
Vichayanun

**Comment by simoninithomas** [comment]
Oh yes my bad, I merge it in that case thanks for the update 🤗

**Pull request merged**
