### PR TITLE
unit2: Use tqdm in train template

### PR DESCRIPTION
**Pull request by discordianfish**

### CODE REVIEW

**Comment by simoninithomas** [comment]
@osanseviero is tqdm is installed by default on colab? If not I should add it to the requirements.txt 🤔

**Comment by osanseviero** [comment]
Afaik it's installed by default, but always good to add, specially as some users might not be following in Colab but running locally.

**Review by simoninithomas — APPROVED** [review]
LGTM I'm just updating the requirements.txt

**Comment by simoninithomas** [comment]
I merge thanks @discordianfish for your update 🤗

**Pull request merged**
